
author: starboychina
author_url: https://github.com/Xinguang
root_url: http://Xinguang.github.io/WechatKit/
github_url: https://github.com/Xinguang/WechatKit
github_file_prefix: https://github.com/Xinguang/WechatKit/tree/master
theme: jazzy-theme
